CREATE TABLE EMPLOYEE
(
    PERSONAL_NUMBER INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    ENTERPRISE_ID VARCHAR(255) NOT NULL
);
